spring.application.name=AuthXApplication

spring.datasource.url=jdbc:mysql://localhost:3306/AuthXApplication
spring.datasource.username=root
spring.datasource.password=S@itama00
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
